version: '3.1'

services:
  db:
    image: mysql:5.7
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
